version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web_attack_awareness
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-secret-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=web-attack-events
    depends_on:
      - db
      - influxdb

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web_attack_awareness
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.6
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=web-attack-events
      - INFLUXDB_TOKEN=my-secret-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"

volumes:
  postgres_data:
  influxdb_data:
